models:
  gpt35:
    name: "gpt-3.5-turbo"
    api_key_env: "OPENAI_API_KEY"
    max_tokens: 500
    temperature: 0.7
    
  claude:
    name: "claude-3-haiku-20240307"
    api_key_env: "ANTHROPIC_API_KEY"
    max_tokens: 500
    temperature: 0.7
    
  gemini:
    name: "gemini-1.5-flash"
    api_key_env: "GEMINI_API_KEY"
    max_tokens: 500
    temperature: 0.7
